baseURL = "https://www.nictconsultants.com/"
languageCode = "en-us"
title = "Napitalai Information and Communication Technology Consultants | YOUR ICT NEED IS OUR CONCERN"
#theme = "navigator-hugo"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Portfolio"
        url     = "/portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6
    
    # Footer Service Menu
    [[menu.service]]
        name    = "Graphic Design"
        url     = "/service"
        weight  = 1
    [[menu.service]]
        name    = "Web Design"
        url     = "/service"
        weight  = 2
    [[menu.service]]
        name    = "Web Development"
        url     = "/service"
        weight  = 3

    [[menu.nav]]
        name    = "Downloads"
        url     = "/downloads"
        weight  = 4

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "Partners"
        url     = "/about"
        weight  = 1
    [[menu.quicklink]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.quicklink]]
        name    = "FAQ's"
        url     = "/about"
        weight  = 3
    [[menu.quicklink]]
        name    = "Badges"
        url     = "/about"
        weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    footerDescription = "Change the footer decription."

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "NAPITALAI ICT CONSULTANTS"
        description = "Your Information Comunication Technology needs is our major concern here at NICTC."
        button  = true
        btnText = "Know More"
        btnURL  = "https://www.nictconsultants.com/about/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "We have explored the digital landscape with passion for a long time"
        description = "About description"

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "KNOWLEDGE IS POWER!"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= "Call to Action subtitle."
        btnText = "Contact Us"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= "If you have any problems,please don't hesitate to contact us."
        address = "M66,PNGUNITECH  <br>Lae , Morobe"
        phone   = "+675 73127529"
        fax     = "+675 73127529"
        facebook= "https://www.facebook.com/alois.napitalai"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "-6.67152"
        mapLongitude= "146.99836"
        mapMarker   = "images/marker.png"
