backend:
  name: git-gateway
  branch : master
  repo: anapitalai/www.nictconsultants.com # Path to Github repository
  publish_mode: editorial_workflow


media_folder: "static/images"
public_folder: "/images"


collections:
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}


